/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HajjIndexRouteImport } from './routes/hajj.index'
import { Route as HajjCityRouteImport } from './routes/hajj.$city'
import { Route as UmrahIndexRouteImport } from './routes/umrah.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HajjIndexRoute = HajjIndexRouteImport.update({
  id: '/hajj/',
  path: '/hajj/',
  getParentRoute: () => rootRouteImport,
} as any)
const HajjCityRoute = HajjCityRouteImport.update({
  id: '/hajj/$city',
  path: '/hajj/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const UmrahIndexRoute = UmrahIndexRouteImport.update({
  id: '/umrah/',
  path: '/umrah/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hajj/$city': typeof HajjCityRoute
  '/hajj/': typeof HajjIndexRoute
  '/umrah/': typeof UmrahIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hajj/$city': typeof HajjCityRoute
  '/hajj': typeof HajjIndexRoute
  '/umrah': typeof UmrahIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hajj/$city': typeof HajjCityRoute
  '/hajj/': typeof HajjIndexRoute
  '/umrah/': typeof UmrahIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hajj/$city' | '/hajj/' | '/umrah/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hajj/$city' | '/hajj' | '/umrah'
  id: '__root__' | '/' | '/hajj/$city' | '/hajj/' | '/umrah/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HajjCityRoute: typeof HajjCityRoute
  HajjIndexRoute: typeof HajjIndexRoute
  UmrahIndexRoute: typeof UmrahIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hajj/': {
      id: '/hajj/'
      path: '/hajj'
      fullPath: '/hajj/'
      preLoaderRoute: typeof HajjIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hajj/$city': {
      id: '/hajj/$city'
      path: '/hajj/$city'
      fullPath: '/hajj/$city'
      preLoaderRoute: typeof HajjCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umrah/': {
      id: '/umrah/'
      path: '/umrah'
      fullPath: '/umrah/'
      preLoaderRoute: typeof UmrahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HajjCityRoute: HajjCityRoute,
  HajjIndexRoute: HajjIndexRoute,
  UmrahIndexRoute: UmrahIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
